"""
OFX code generation tools for creating plugin skeletons and common patterns.
"""

from typing import Optional
from ..data import CONTEXTS, PARAM_TYPES, BIT_DEPTHS, IMAGE_COMPONENTS


def generate_plugin_skeleton(
    plugin_name: str,
    plugin_id: str,
    context: str = "kOfxImageEffectContextFilter",
    params: Optional[list[dict]] = None,
    supports_gpu: bool = False,
) -> str:
    """
    Generate a basic OFX plugin skeleton.

    Args:
        plugin_name: Human-readable plugin name
        plugin_id: Unique plugin identifier (e.g., 'com.company.myplugin')
        context: Plugin context
        params: List of parameter definitions
        supports_gpu: Whether to include GPU rendering support

    Returns:
        C++ plugin code skeleton.
    """
    params = params or []

    code = f'''// OFX Plugin: {plugin_name}
// ID: {plugin_id}
// Generated by MCP OFX

#include "ofxImageEffect.h"
#include "ofxMemory.h"
#include "ofxMultiThread.h"

// Plugin identifier
#define PLUGIN_ID "{plugin_id}"
#define PLUGIN_NAME "{plugin_name}"
#define PLUGIN_VERSION_MAJOR 1
#define PLUGIN_VERSION_MINOR 0

// Global host pointers
static OfxHost *gHost = NULL;
static OfxPropertySuiteV1 *gPropSuite = NULL;
static OfxImageEffectSuiteV1 *gEffectSuite = NULL;
static OfxParameterSuiteV1 *gParamSuite = NULL;
static OfxMemorySuiteV1 *gMemorySuite = NULL;
static OfxMultiThreadSuiteV1 *gThreadSuite = NULL;

// Instance data structure
typedef struct {{
    OfxImageEffectHandle effect;
    OfxImageClipHandle sourceClip;
    OfxImageClipHandle outputClip;
{_generate_param_handles(params)}
}} PluginInstance;

//------------------------------------------------------------------------------
// Suite fetching
//------------------------------------------------------------------------------
static OfxStatus fetchSuites(void)
{{
    gPropSuite = (OfxPropertySuiteV1*)gHost->fetchSuite(
        gHost->host, kOfxPropertySuite, 1);
    gEffectSuite = (OfxImageEffectSuiteV1*)gHost->fetchSuite(
        gHost->host, kOfxImageEffectSuite, 1);
    gParamSuite = (OfxParameterSuiteV1*)gHost->fetchSuite(
        gHost->host, kOfxParameterSuite, 1);
    gMemorySuite = (OfxMemorySuiteV1*)gHost->fetchSuite(
        gHost->host, kOfxMemorySuite, 1);
    gThreadSuite = (OfxMultiThreadSuiteV1*)gHost->fetchSuite(
        gHost->host, kOfxMultiThreadSuite, 1);

    if (!gPropSuite || !gEffectSuite || !gParamSuite) {{
        return kOfxStatErrMissingHostFeature;
    }}
    return kOfxStatOK;
}}

//------------------------------------------------------------------------------
// Load Action
//------------------------------------------------------------------------------
static OfxStatus onLoad(void)
{{
    return fetchSuites();
}}

//------------------------------------------------------------------------------
// Describe Action
//------------------------------------------------------------------------------
static OfxStatus describe(OfxImageEffectHandle effect)
{{
    OfxPropertySetHandle props;
    gEffectSuite->getPropertySet(effect, &props);

    // Set plugin properties
    gPropSuite->propSetString(props, kOfxPropLabel, 0, PLUGIN_NAME);
    gPropSuite->propSetString(props, kOfxImageEffectPluginPropGrouping, 0, "MCP OFX");

    // Supported contexts
    gPropSuite->propSetString(props, kOfxImageEffectPropSupportedContexts, 0,
                              {_context_string(context)});

    // Supported pixel depths
    gPropSuite->propSetString(props, kOfxImageEffectPropSupportedPixelDepths, 0, kOfxBitDepthFloat);
    gPropSuite->propSetString(props, kOfxImageEffectPropSupportedPixelDepths, 1, kOfxBitDepthShort);
    gPropSuite->propSetString(props, kOfxImageEffectPropSupportedPixelDepths, 2, kOfxBitDepthByte);

    // Capabilities
    gPropSuite->propSetInt(props, kOfxImageEffectPropSupportsMultiResolution, 0, 1);
    gPropSuite->propSetInt(props, kOfxImageEffectPropSupportsTiles, 0, 1);
    gPropSuite->propSetInt(props, kOfxImageEffectPropTemporalClipAccess, 0, 0);
    gPropSuite->propSetString(props, kOfxImageEffectPluginRenderThreadSafety, 0,
                              kOfxImageEffectRenderFullySafe);
{_generate_gpu_describe(supports_gpu)}
    return kOfxStatOK;
}}

//------------------------------------------------------------------------------
// Describe in Context Action
//------------------------------------------------------------------------------
static OfxStatus describeInContext(OfxImageEffectHandle effect, OfxPropertySetHandle inArgs)
{{
    OfxPropertySetHandle props;

    // Define source clip
    gEffectSuite->clipDefine(effect, "Source", &props);
    gPropSuite->propSetString(props, kOfxImageEffectPropSupportedComponents, 0, kOfxImageComponentRGBA);
    gPropSuite->propSetString(props, kOfxImageEffectPropSupportedComponents, 1, kOfxImageComponentRGB);
    gPropSuite->propSetString(props, kOfxImageEffectPropSupportedComponents, 2, kOfxImageComponentAlpha);

    // Define output clip
    gEffectSuite->clipDefine(effect, "Output", &props);
    gPropSuite->propSetString(props, kOfxImageEffectPropSupportedComponents, 0, kOfxImageComponentRGBA);
    gPropSuite->propSetString(props, kOfxImageEffectPropSupportedComponents, 1, kOfxImageComponentRGB);
    gPropSuite->propSetString(props, kOfxImageEffectPropSupportedComponents, 2, kOfxImageComponentAlpha);

    // Define parameters
    OfxParamSetHandle paramSet;
    gEffectSuite->getParamSet(effect, &paramSet);
{_generate_param_defines(params)}
    return kOfxStatOK;
}}

//------------------------------------------------------------------------------
// Create Instance Action
//------------------------------------------------------------------------------
static OfxStatus createInstance(OfxImageEffectHandle effect)
{{
    PluginInstance *instance = NULL;
    gMemorySuite->memoryAlloc(NULL, sizeof(PluginInstance), (void**)&instance);
    if (!instance) return kOfxStatErrMemory;

    instance->effect = effect;
    gEffectSuite->clipGetHandle(effect, "Source", &instance->sourceClip, NULL);
    gEffectSuite->clipGetHandle(effect, "Output", &instance->outputClip, NULL);
{_generate_param_fetch(params)}
    OfxPropertySetHandle props;
    gEffectSuite->getPropertySet(effect, &props);
    gPropSuite->propSetPointer(props, kOfxPropInstanceData, 0, instance);

    return kOfxStatOK;
}}

//------------------------------------------------------------------------------
// Destroy Instance Action
//------------------------------------------------------------------------------
static OfxStatus destroyInstance(OfxImageEffectHandle effect)
{{
    OfxPropertySetHandle props;
    gEffectSuite->getPropertySet(effect, &props);

    PluginInstance *instance = NULL;
    gPropSuite->propGetPointer(props, kOfxPropInstanceData, 0, (void**)&instance);

    if (instance) {{
        gMemorySuite->memoryFree(instance);
    }}
    return kOfxStatOK;
}}

//------------------------------------------------------------------------------
// Is Identity Action
//------------------------------------------------------------------------------
static OfxStatus isIdentity(OfxImageEffectHandle effect,
                            OfxPropertySetHandle inArgs,
                            OfxPropertySetHandle outArgs)
{{
    // Return kOfxStatOK if this effect is an identity (pass-through)
    // Set kOfxPropName to clip name and kOfxPropTime to time to use
    return kOfxStatReplyDefault;
}}

//------------------------------------------------------------------------------
// Render Action
//------------------------------------------------------------------------------
static OfxStatus render(OfxImageEffectHandle effect, OfxPropertySetHandle inArgs)
{{
    OfxPropertySetHandle props;
    gEffectSuite->getPropertySet(effect, &props);

    PluginInstance *instance = NULL;
    gPropSuite->propGetPointer(props, kOfxPropInstanceData, 0, (void**)&instance);
    if (!instance) return kOfxStatErrBadHandle;

    // Get render arguments
    OfxTime time;
    gPropSuite->propGetDouble(inArgs, kOfxPropTime, 0, &time);

    OfxRectI renderWindow;
    gPropSuite->propGetIntN(inArgs, kOfxImageEffectPropRenderWindow, 4, &renderWindow.x1);

    double renderScale[2];
    gPropSuite->propGetDoubleN(inArgs, kOfxImageEffectPropRenderScale, 2, renderScale);

    // Fetch images
    OfxPropertySetHandle sourceImg = NULL, outputImg = NULL;
    gEffectSuite->clipGetImage(instance->sourceClip, time, NULL, &sourceImg);
    gEffectSuite->clipGetImage(instance->outputClip, time, NULL, &outputImg);

    if (!sourceImg || !outputImg) {{
        if (sourceImg) gEffectSuite->clipReleaseImage(sourceImg);
        if (outputImg) gEffectSuite->clipReleaseImage(outputImg);
        return kOfxStatFailed;
    }}

    // Get image properties
    void *srcData = NULL, *dstData = NULL;
    gPropSuite->propGetPointer(sourceImg, kOfxImagePropData, 0, &srcData);
    gPropSuite->propGetPointer(outputImg, kOfxImagePropData, 0, &dstData);

    int srcRowBytes, dstRowBytes;
    gPropSuite->propGetInt(sourceImg, kOfxImagePropRowBytes, 0, &srcRowBytes);
    gPropSuite->propGetInt(outputImg, kOfxImagePropRowBytes, 0, &dstRowBytes);

    OfxRectI srcBounds, dstBounds;
    gPropSuite->propGetIntN(sourceImg, kOfxImagePropBounds, 4, &srcBounds.x1);
    gPropSuite->propGetIntN(outputImg, kOfxImagePropBounds, 4, &dstBounds.x1);

    char *pixelDepth = NULL;
    gPropSuite->propGetString(outputImg, kOfxImageEffectPropPixelDepth, 0, &pixelDepth);

    char *components = NULL;
    gPropSuite->propGetString(outputImg, kOfxImageEffectPropComponents, 0, &components);

    // Get parameter values at render time
{_generate_param_get_values(params)}
    // TODO: Implement your pixel processing here
    // Process renderWindow region using srcData -> dstData

    // Release images
    gEffectSuite->clipReleaseImage(sourceImg);
    gEffectSuite->clipReleaseImage(outputImg);

    return kOfxStatOK;
}}

//------------------------------------------------------------------------------
// Main Entry Point
//------------------------------------------------------------------------------
static OfxStatus pluginMain(const char *action,
                            const void *handle,
                            OfxPropertySetHandle inArgs,
                            OfxPropertySetHandle outArgs)
{{
    if (strcmp(action, kOfxActionLoad) == 0) {{
        return onLoad();
    }}
    if (strcmp(action, kOfxActionDescribe) == 0) {{
        return describe((OfxImageEffectHandle)handle);
    }}
    if (strcmp(action, kOfxImageEffectActionDescribeInContext) == 0) {{
        return describeInContext((OfxImageEffectHandle)handle, inArgs);
    }}
    if (strcmp(action, kOfxActionCreateInstance) == 0) {{
        return createInstance((OfxImageEffectHandle)handle);
    }}
    if (strcmp(action, kOfxActionDestroyInstance) == 0) {{
        return destroyInstance((OfxImageEffectHandle)handle);
    }}
    if (strcmp(action, kOfxImageEffectActionIsIdentity) == 0) {{
        return isIdentity((OfxImageEffectHandle)handle, inArgs, outArgs);
    }}
    if (strcmp(action, kOfxImageEffectActionRender) == 0) {{
        return render((OfxImageEffectHandle)handle, inArgs);
    }}
    // Handle other actions...
    return kOfxStatReplyDefault;
}}

//------------------------------------------------------------------------------
// setHost callback
//------------------------------------------------------------------------------
static void setHost(OfxHost *host)
{{
    gHost = host;
}}

//------------------------------------------------------------------------------
// Plugin definition
//------------------------------------------------------------------------------
static OfxPlugin plugin = {{
    kOfxImageEffectPluginApi,
    kOfxImageEffectPluginApiVersion,
    PLUGIN_ID,
    PLUGIN_VERSION_MAJOR,
    PLUGIN_VERSION_MINOR,
    setHost,
    pluginMain
}};

//------------------------------------------------------------------------------
// Exported functions
//------------------------------------------------------------------------------
OfxExport int OfxGetNumberOfPlugins(void)
{{
    return 1;
}}

OfxExport OfxPlugin* OfxGetPlugin(int nth)
{{
    if (nth == 0) return &plugin;
    return NULL;
}}
'''
    return code


def _context_string(context: str) -> str:
    """Convert context constant to string."""
    context_map = {
        "kOfxImageEffectContextFilter": "kOfxImageEffectContextFilter",
        "kOfxImageEffectContextGenerator": "kOfxImageEffectContextGenerator",
        "kOfxImageEffectContextTransition": "kOfxImageEffectContextTransition",
        "kOfxImageEffectContextGeneral": "kOfxImageEffectContextGeneral",
        "kOfxImageEffectContextRetimer": "kOfxImageEffectContextRetimer",
        "kOfxImageEffectContextPaint": "kOfxImageEffectContextPaint",
    }
    return context_map.get(context, "kOfxImageEffectContextFilter")


def _generate_param_handles(params: list[dict]) -> str:
    """Generate parameter handle declarations."""
    if not params:
        return "    // Add parameter handles here"

    lines = []
    for param in params:
        name = param.get("name", "param")
        lines.append(f"    OfxParamHandle {name}Param;")
    return "\n".join(lines)


def _generate_param_defines(params: list[dict]) -> str:
    """Generate parameter definition code."""
    if not params:
        return """
    // Example: Define a double parameter
    // gParamSuite->paramDefine(paramSet, kOfxParamTypeDouble, "amount", &props);
    // gPropSuite->propSetString(props, kOfxPropLabel, 0, "Amount");
    // gPropSuite->propSetDouble(props, kOfxParamPropDefault, 0, 1.0);
    // gPropSuite->propSetDouble(props, kOfxParamPropMin, 0, 0.0);
    // gPropSuite->propSetDouble(props, kOfxParamPropMax, 0, 10.0);
"""
    lines = ["\n"]
    for param in params:
        name = param.get("name", "param")
        label = param.get("label", name)
        ptype = param.get("type", "kOfxParamTypeDouble")
        default = param.get("default", 0)
        pmin = param.get("min", None)
        pmax = param.get("max", None)

        lines.append(f'    gParamSuite->paramDefine(paramSet, {ptype}, "{name}", &props);')
        lines.append(f'    gPropSuite->propSetString(props, kOfxPropLabel, 0, "{label}");')

        if ptype in ["kOfxParamTypeDouble", "kOfxParamTypeInteger"]:
            dtype = "Double" if "Double" in ptype else "Int"
            lines.append(f"    gPropSuite->propSet{dtype}(props, kOfxParamPropDefault, 0, {default});")
            if pmin is not None:
                lines.append(f"    gPropSuite->propSet{dtype}(props, kOfxParamPropMin, 0, {pmin});")
            if pmax is not None:
                lines.append(f"    gPropSuite->propSet{dtype}(props, kOfxParamPropMax, 0, {pmax});")
        elif ptype == "kOfxParamTypeBoolean":
            lines.append(f"    gPropSuite->propSetInt(props, kOfxParamPropDefault, 0, {1 if default else 0});")

        lines.append("")

    return "\n".join(lines)


def _generate_param_fetch(params: list[dict]) -> str:
    """Generate parameter fetch code for create instance."""
    if not params:
        return "    // Fetch parameter handles here"

    lines = ["\n    OfxParamSetHandle paramSet;", "    gEffectSuite->getParamSet(effect, &paramSet);"]
    for param in params:
        name = param.get("name", "param")
        lines.append(f'    gParamSuite->paramGetHandle(paramSet, "{name}", &instance->{name}Param, NULL);')
    return "\n".join(lines)


def _generate_param_get_values(params: list[dict]) -> str:
    """Generate code to get parameter values at render time."""
    if not params:
        return "    // Get parameter values here"

    lines = []
    for param in params:
        name = param.get("name", "param")
        ptype = param.get("type", "kOfxParamTypeDouble")

        if "Double" in ptype:
            dims = 1
            if "2D" in ptype:
                dims = 2
            elif "3D" in ptype:
                dims = 3
            if dims == 1:
                lines.append(f"    double {name}Value;")
                lines.append(f"    gParamSuite->paramGetValueAtTime(instance->{name}Param, time, &{name}Value);")
            else:
                lines.append(f"    double {name}Value[{dims}];")
                varargs = ", ".join([f"&{name}Value[{i}]" for i in range(dims)])
                lines.append(f"    gParamSuite->paramGetValueAtTime(instance->{name}Param, time, {varargs});")
        elif "Integer" in ptype:
            lines.append(f"    int {name}Value;")
            lines.append(f"    gParamSuite->paramGetValueAtTime(instance->{name}Param, time, &{name}Value);")
        elif ptype == "kOfxParamTypeBoolean":
            lines.append(f"    int {name}Value;")
            lines.append(f"    gParamSuite->paramGetValueAtTime(instance->{name}Param, time, &{name}Value);")

    return "\n".join(lines)


def _generate_gpu_describe(supports_gpu: bool) -> str:
    """Generate GPU support properties."""
    if not supports_gpu:
        return ""
    return '''
    // GPU Rendering support
    gPropSuite->propSetString(props, kOfxImageEffectPropCudaRenderSupported, 0, "true");
    gPropSuite->propSetString(props, kOfxImageEffectPropMetalRenderSupported, 0, "true");
    gPropSuite->propSetString(props, kOfxImageEffectPropOpenCLRenderSupported, 0, "true");
'''


def generate_parameter_code(
    param_name: str,
    param_type: str,
    label: Optional[str] = None,
    default: Optional[any] = None,
    min_val: Optional[any] = None,
    max_val: Optional[any] = None,
    hint: Optional[str] = None,
) -> str:
    """
    Generate code for defining a single parameter.

    Args:
        param_name: Parameter name
        param_type: Parameter type constant
        label: Display label
        default: Default value
        min_val: Minimum value
        max_val: Maximum value
        hint: Tooltip hint

    Returns:
        C code for parameter definition.
    """
    label = label or param_name
    lines = [
        f'// Define {param_name} parameter',
        f'gParamSuite->paramDefine(paramSet, {param_type}, "{param_name}", &props);',
        f'gPropSuite->propSetString(props, kOfxPropLabel, 0, "{label}");',
    ]

    if hint:
        lines.append(f'gPropSuite->propSetString(props, kOfxParamPropHint, 0, "{hint}");')

    # Type-specific properties
    if param_type in ["kOfxParamTypeDouble", "kOfxParamTypeDouble2D", "kOfxParamTypeDouble3D"]:
        if default is not None:
            if isinstance(default, (list, tuple)):
                for i, val in enumerate(default):
                    lines.append(f"gPropSuite->propSetDouble(props, kOfxParamPropDefault, {i}, {val});")
            else:
                lines.append(f"gPropSuite->propSetDouble(props, kOfxParamPropDefault, 0, {default});")
        if min_val is not None:
            if isinstance(min_val, (list, tuple)):
                for i, val in enumerate(min_val):
                    lines.append(f"gPropSuite->propSetDouble(props, kOfxParamPropMin, {i}, {val});")
            else:
                lines.append(f"gPropSuite->propSetDouble(props, kOfxParamPropMin, 0, {min_val});")
        if max_val is not None:
            if isinstance(max_val, (list, tuple)):
                for i, val in enumerate(max_val):
                    lines.append(f"gPropSuite->propSetDouble(props, kOfxParamPropMax, {i}, {val});")
            else:
                lines.append(f"gPropSuite->propSetDouble(props, kOfxParamPropMax, 0, {max_val});")

    elif param_type in ["kOfxParamTypeInteger", "kOfxParamTypeInteger2D", "kOfxParamTypeInteger3D"]:
        if default is not None:
            if isinstance(default, (list, tuple)):
                for i, val in enumerate(default):
                    lines.append(f"gPropSuite->propSetInt(props, kOfxParamPropDefault, {i}, {val});")
            else:
                lines.append(f"gPropSuite->propSetInt(props, kOfxParamPropDefault, 0, {default});")
        if min_val is not None:
            lines.append(f"gPropSuite->propSetInt(props, kOfxParamPropMin, 0, {min_val});")
        if max_val is not None:
            lines.append(f"gPropSuite->propSetInt(props, kOfxParamPropMax, 0, {max_val});")

    elif param_type == "kOfxParamTypeBoolean":
        if default is not None:
            lines.append(f"gPropSuite->propSetInt(props, kOfxParamPropDefault, 0, {1 if default else 0});")

    elif param_type in ["kOfxParamTypeRGB", "kOfxParamTypeRGBA"]:
        if default is not None:
            for i, val in enumerate(default):
                lines.append(f"gPropSuite->propSetDouble(props, kOfxParamPropDefault, {i}, {val});")

    return "\n".join(lines)
